export const WORKOUTS_ROUTINES_GET = "WORKOUTS_ROUTINES_GET";
export const WORKOUTS_ROUTINES_SUCCESS = "WORKOUTS_ROUTINES_SUCCESS";
export const WORKOUTS_ROUTINES_FAILURE = "WORKOUTS_ROUTINES_FAILURE";
